/* Bacchetta legacy loader — superseded by market-sync-v50.js v3.4.54 */
(function(){
'use strict';
const VERSION='3.4.54',ROLE_WEIGHT={P:1,D:1,C:1.05,A:1.1},PRIORITY_VALUE={max:1,high:.9,base:.78,low:.62,bet:.52},HIST_WEIGHT={P:.35,D:.40,C:.40,A:.40},BEAM_WIDTH=48,CANDIDATE_LIMIT=24,CHEAP_LIMIT=6;
function all(){return typeof allPlayers==='function'?allPlayers():[]}function limits(){return typeof roleLimits==='function'?roleLimits():{P:2,D:9,C:9,A:7}}function myTeam(){return typeof brainMyTeam==='function'?brainMyTeam():current?.teams?.[0]||null}function soldIds(){const s=new Set();(current?.teams||[]).forEach(t=>(t.players||[]).forEach(p=>s.add(String(p.id))));return s}function activeStrategy(){return typeof activeBrainStrategy==='function'?activeBrainStrategy():current?.brainStrategies?.find(s=>s.id===current?.activeBrainStrategyId)}function strategySlots(s){return typeof brainStrategySlots==='function'?brainStrategySlots(s):limits()}function slotPct(s,r){return typeof brainStrategySlotAllocation==='function'?brainStrategySlotAllocation(s,r):Array.from({length:strategySlots(s)[r]||0},()=>100/(strategySlots(s)[r]||1))}function targetFor(s,r,i){const a=s?.slotTargets?.[r],t=Array.isArray(a)&&a[i]?a[i]:null;return t?{priority:t.priority||'base',playerId:t.playerId??null}:{priority:'base',playerId:null}}
function inject(){const version=document.querySelector('.app-version');if(version)version.textContent='V. '+VERSION;const brain=document.getElementById('brain');if(!brain)return;const head=brain.querySelector('.h2')?.parentElement;if(!head)return;let btn=head.querySelector('.magic-wand-btn');if(!btn){btn=document.createElement('button');btn.type='button';btn.className='magic-wand-btn';btn.textContent='🪄';btn.title='Ricalcola tutta la strategia';btn.setAttribute('aria-label','Ricalcola tutta la strategia');head.appendChild(btn)}}
function style(){if(document.getElementById('magicWandStyle'))return;const s=document.createElement('style');s.id='magicWandStyle';s.textContent=`.magic-wand-btn{width:42px;height:42px;flex:0 0 42px;border:1px solid #dfe4e9;border-radius:13px;background:#fff;font-size:23px;display:flex;align-items:center;justify-content:center;box-shadow:0 1px 4px rgba(20,30,45,.06);cursor:pointer}.magic-wand-btn:active{transform:scale(.92)}.magic-wand-btn.magic-wand-running{animation:magicWandPulse .72s ease-in-out infinite;box-shadow:0 0 0 6px rgba(8,120,79,.10),0 3px 14px rgba(8,120,79,.20);background:#f2fbf7}.magic-wand-btn:disabled{cursor:wait}@keyframes magicWandPulse{0%,100%{transform:scale(1) rotate(0deg)}50%{transform:scale(1.10) rotate(8deg)}}`;document.head.appendChild(s)}
function start(){style();inject();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
