/* Brain engine 3.5.89 — prezzi reali delle schede + gerarchia + scommesse low cost */
(function(){
'use strict';
const VERSION='3.5.89',ROLES=['P','D','C','A'],RANK={max:4,high:3,low:2,bet:1,base:0};
let busy=false;
function state(){try{return(typeof current!=='undefined'&&current)||JSON.parse(localStorage.getItem('AF_CURRENT')||'null')}catch(e){return null}}
function players(){try{return typeof window.allPlayers==='function'?window.allPlayers():[]}catch(e){return[]}}
function strategy(s){return(s?.brainStrategies||[]).find(x=>Number(x.id)===Number(s.activeBrainStrategyId))||null}
function mine(s){return(s?.teams||[]).find(t=>Number(t.id)===Number(s.myTeamId))||(s?.teams||[])[0]||null}
function sold(s){const x=new Set();(s?.teams||[]).forEach(t=>(t.players||[]).forEach(p=>x.add(String(p.id))));return x}
function priority(s,id){try{const v=window.objectivePriority?.(id);if(RANK[v]!=null)return v}catch(e){}const v=s?.objectivePriorities?.[id]??s?.objectivePriorities?.[String(id)];return RANK[v]!=null?v:'low'}
function allocation(st,r){const a=st?.baseAllocation&&typeof st.baseAllocation==='object'?st.baseAllocation:(st?.allocation||{});return Math.max(0,Number(a[r])||0)}
function roleBudget(s,st,r){return Math.max(0,Math.round((Number(s?.initialCredits)||1200)*allocation(st,r)/100))}
function capFor(s,st,r){return Math.max(30,Math.round(roleBudget(s,st,r)*.10))}
function ensure(st,r,n){st.slotTargets=st.slotTargets&&typeof st.slotTargets==='object'?st.slotTargets:{};st.slotTargets[r]=Array.isArray(st.slotTargets[r])?st.slotTargets[r]:[];while(st.slotTargets[r].length<n)st.slotTargets[r].push({priority:'base',playerId:null});st.slotTargets[r]=st.slotTargets[r].slice(0,n);st.slotBudgets=st.slotBudgets&&typeof st.slotBudgets==='object'?st.slotBudgets:{};st.slotBudgets[r]=Array.isArray(st.slotBudgets[r])?st.slotBudgets[r]:[];while(st.slotBudgets[r].length<n)st.slotBudgets[r].push(0);st.slotBudgets[r]=st.slotBudgets[r].slice(0,n);st.slotBudgetManual=st.slotBudgetManual&&typeof st.slotBudgetManual==='object'?st.slotBudgetManual:{};st.slotBudgetManual[r]=Array.isArray(st.slotBudgetManual[r])?st.slotBudgetManual[r]:[];while(st.slotBudgetManual[r].length<n)st.slotBudgetManual[r].push(false);st.slotBudgetManual[r]=st.slotBudgetManual[r].slice(0,n)}
function findPlayer(s,st,r,i,slot){const list=players(),el=slot?.querySelector?.('.brain-slot-player'),name=String(el?.textContent||'').trim().toLowerCase();if(name&&name!=='scegli giocatore'){const byName=list.find(x=>String(x.name||'').trim().toLowerCase()===name&&String(x.role||'').toUpperCase()===r);if(byName)return byName}const id=st?.slotTargets?.[r]?.[i]?.playerId;if(id!=null){const byId=list.find(x=>String(x.id)===String(id)&&String(x.role||'').toUpperCase()===r);if(byId)return byId}return null}
function cardCredits(p){const c=Number(p?.credits);return Number.isFinite(c)&&c>=0?c:null}
function syncCredits(){const s=state(),st=strategy(s);if(!s||!st)return false;let changed=false;ROLES.forEach(r=>{const n=Math.max(0,Math.round(Number(st.slots?.[r])||0));ensure(st,r,n);const row=document.querySelector('#brainContent .brain-role-row.role-'+r);if(!row)return;[...row.querySelectorAll('.brain-slot')].forEach((slot,i)=>{if(slot.classList.contains('purchased'))return;const p=findPlayer(s,st,r,i,slot),c=cardCredits(p);if(c==null)return;if(st.slotBudgetManual?.[r]?.[i]===true)st.slotBudgetManual[r][i]=false;if(Number(st.slotBudgets[r][i])!==c){st.slotBudgets[r][i]=c;changed=true}});});return changed}
function score(p,s,r){const my=mine(s),same=(my?.players||[]).some(x=>x.role===r&&String(x.realTeam||x.team||'').toLowerCase()===String(p.team||'').toLowerCase());return(Number(p.appeal)||0)*18+(same?-9:5)}
function candidates(s,st,r,required,used){const obj=new Set((s.objectives||[]).map(String)),soldSet=sold(s),pool=players().filter(p=>String(p.role||'').toUpperCase()===r&&!soldSet.has(String(p.id))&&!used.has(String(p.id))&&obj.has(String(p.id))&&cardCredits(p)>0),exact=pool.filter(p=>priority(s,p.id)===required);return exact.length?exact:pool}
function choose(s,st,t,used,cap){let list=candidates(s,st,t.r,t.priority,used);if(t.priority==='bet'){const hard=Math.min(cap,capFor(s,st,t.r));list=list.filter(p=>cardCredits(p)<=hard);list.sort((a,b)=>{const ac=Math.max(.1,cardCredits(a)),bc=Math.max(.1,cardCredits(b));return score(b,s,t.r)/bc-score(a,s,t.r)/ac||score(b,s,t.r)-score(a,s,t.r)||ac-bc});return list[0]||null}list=list.filter(p=>cardCredits(p)<=cap);list.sort((a,b)=>score(b,s,t.r)-score(a,s,t.r)||Number(b.appeal||0)-Number(a.appeal||0)||cardCredits(a)-cardCredits(b));return list[0]||null}
function replaceExpensiveBets(s,st,used){ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach((t,i)=>{if(!t||t.priority!=='bet'||t.playerId==null)return;const p=players().find(x=>String(x.id)===String(t.playerId)),c=cardCredits(p),cap=capFor(s,st,r);if(c!=null&&c<=cap)return;used.delete(String(t.playerId));const alt=choose(s,st,{r,priority:'bet'},used,cap);if(alt){t.playerId=alt.id;st.slotBudgets[r][i]=cardCredits(alt);used.add(String(alt.id))}else{t.playerId=null;st.slotBudgets[r][i]=0}}))}
function sanitize(){const s=state(),st=strategy(s);if(!s||!st)return false;const used=new Set((mine(s)?.players||[]).map(p=>String(p.id)));ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach(t=>{if(t?.playerId!=null)used.add(String(t.playerId))}));replaceExpensiveBets(s,st,used);return syncCredits()}
function installRendererPolicy(){if(typeof window.brainStrategySlotAllocation!=='function')return false;if(window.brainStrategySlotAllocation.__brainEngine389)return true;const original=window.brainStrategySlotAllocation;const wrapped=function(s,r){const out=original.apply(this,arguments);const st=strategy(s),role=String(r||'').toUpperCase();if(!st||!Array.isArray(out)||!ROLES.includes(role))return out;const list=Array.isArray(st.slotTargets?.[role])?st.slotTargets[role]:[];const plan=roleBudget(s,st,role),all=players(),result=out.slice();for(let i=0;i<result.length;i++){const t=list[i];if(!t||t.playerId==null||plan<=0)continue;const p=all.find(x=>String(x.id)===String(t.playerId)&&String(x.role||'').toUpperCase()===role);const c=cardCredits(p);if(c!=null){/* percentuale a 2 decimali: il renderer continua a calcolare il budget, ma il risultato torna esattamente ai Crediti della scheda */result[i]=Math.round((c/plan*100)*100)/100}}return result};wrapped.__brainEngine389=true;window.brainStrategySlotAllocation=wrapped;return true}
function fill(){if(busy)return;const s=state(),st=strategy(s);if(!s||!st)return;busy=true;try{const used=new Set((mine(s)?.players||[]).map(p=>String(p.id)));ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach(t=>{if(t?.playerId!=null)used.add(String(t.playerId))}));replaceExpensiveBets(s,st,used);const tasks=[];ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach((t,i)=>{if(t?.playerId==null)tasks.push({r,i,priority:t?.priority||'base'})}));tasks.sort((a,b)=>(RANK[b.priority]??0)-(RANK[a.priority]??0)||ROLES.indexOf(a.r)-ROLES.indexOf(b.r));for(const t of tasks){const cap=roleBudget(s,st,t.r),p=choose(s,st,t,used,cap);if(!p)continue;t.playerId=p.id;st.slotBudgets[t.r][t.i]=cardCredits(p);used.add(String(p.id))}sanitize();if(typeof window.persist==='function')window.persist();else{localStorage.setItem('AF_CURRENT',JSON.stringify(s));const db=JSON.parse(localStorage.getItem('AF_DB')||'[]'),i=db.findIndex(x=>Number(x.id)===Number(s.id));if(i>=0){db[i]=s;localStorage.setItem('AF_DB',JSON.stringify(db))}}if(typeof window.renderBrain==='function')setTimeout(window.renderBrain,0)}finally{busy=false}}
function patch(){installRendererPolicy();sanitize();const v=document.querySelector('.app-version');if(v)v.textContent='V. '+VERSION}
function boot(){patch();setInterval(patch,300)}
window.BrainEngine={version:VERSION,syncCredits,fill,patch};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
