/* Brain engine 3.5.103 — no polling loop; credits from player cards */
(function(){
'use strict';
const VERSION='3.5.103',ROLES=['P','D','C','A'],RANK={max:4,high:3,low:2,base:1,bet:0};
let busy=false;
function state(){try{return(typeof current!=='undefined'&&current)||JSON.parse(localStorage.getItem('AF_CURRENT')||'null')}catch(e){return null}}
function players(){try{return typeof window.allPlayers==='function'?window.allPlayers():[]}catch(e){return[]}}
function strategy(s){return(s?.brainStrategies||[]).find(x=>Number(x.id)===Number(s.activeBrainStrategyId))||null}
function mine(s){return(s?.teams||[]).find(t=>Number(t.id)===Number(s.myTeamId))||(s?.teams||[])[0]||null}
function sold(s){const x=new Set();(s?.teams||[]).forEach(t=>(t.players||[]).forEach(p=>x.add(String(p.id))));return x}
function priority(s,id){try{const v=window.objectivePriority?.(id);if(RANK[v]!=null)return v}catch(e){}const v=s?.objectivePriorities?.[id]??s?.objectivePriorities?.[String(id)];return RANK[v]!=null?v:'base'}
function allocation(st,r){const a=st?.baseAllocation&&typeof st.baseAllocation==='object'?st.baseAllocation:(st?.allocation||{});return Math.max(0,Number(a[r])||0)}
function roleBudget(s,st,r){return Math.max(0,Math.round((Number(s?.initialCredits)||1200)*allocation(st,r)/100))}
function roleSpent(s,r){const my=mine(s);return Math.round((my?.players||[]).filter(p=>String(p.role||'').toUpperCase()===r).reduce((n,p)=>n+Math.max(0,Number(p.price)||0),0))}
function betCap(s,st,r){return Math.max(30,Math.round(roleBudget(s,st,r)*.10))}
function ensure(st,r,n){st.slotTargets=st.slotTargets&&typeof st.slotTargets==='object'?st.slotTargets:{};st.slotTargets[r]=Array.isArray(st.slotTargets[r])?st.slotTargets[r]:[];while(st.slotTargets[r].length<n)st.slotTargets[r].push({priority:'base',playerId:null});st.slotTargets[r]=st.slotTargets[r].slice(0,n);st.slotBudgets=st.slotBudgets&&typeof st.slotBudgets==='object'?st.slotBudgets:{};st.slotBudgets[r]=Array.isArray(st.slotBudgets[r])?st.slotBudgets[r]:[];while(st.slotBudgets[r].length<n)st.slotBudgets[r].push(0);st.slotBudgets[r]=st.slotBudgets[r].slice(0,n);st.slotBudgetManual=st.slotBudgetManual&&typeof st.slotBudgetManual==='object'?st.slotBudgetManual:{};st.slotBudgetManual[r]=Array.isArray(st.slotBudgetManual[r])?st.slotBudgetManual[r]:[];while(st.slotBudgetManual[r].length<n)st.slotBudgetManual[r].push(false);st.slotBudgetManual[r]=st.slotBudgetManual[r].slice(0,n)}
function cardCredits(p){const c=Number(p?.credits);return Number.isFinite(c)&&c>=0?Math.round(c):null}
function findPlayer(s,st,r,i,slot){const list=players(),el=slot?.querySelector?.('.brain-slot-player'),name=String(el?.textContent||'').trim().toLowerCase();if(name&&name!=='scegli giocatore'){const p=list.find(x=>String(x.name||'').trim().toLowerCase()===name&&String(x.role||'').toUpperCase()===r);if(p)return p}const id=st?.slotTargets?.[r]?.[i]?.playerId;if(id!=null)return list.find(x=>String(x.id)===String(id)&&String(x.role||'').toUpperCase()===r)||null;return null}
function syncCredits(){const s=state(),st=strategy(s);if(!s||!st)return false;let changed=false;ROLES.forEach(r=>{const n=Math.max(0,Math.round(Number(st.slots?.[r])||0));ensure(st,r,n);const row=document.querySelector('#brainContent .brain-role-row.role-'+r);if(!row)return;[...row.querySelectorAll('.brain-slot')].forEach((slot,i)=>{if(slot.classList.contains('purchased'))return;const p=findPlayer(s,st,r,i,slot),c=cardCredits(p);if(c==null)return;if(st.slotBudgetManual?.[r]?.[i]===true)st.slotBudgetManual[r][i]=false;if(Number(st.slotBudgets[r][i])!==c){st.slotBudgets[r][i]=c;changed=true}})});return changed}
function score(p,s,r){const my=mine(s),same=(my?.players||[]).some(x=>x.role===r&&String(x.realTeam||x.team||'').toLowerCase()===String(p.team||'').toLowerCase());return(Number(p.appeal)||0)*18+(same?-9:5)}
function candidates(s,r,used){const obj=new Set((s.objectives||[]).map(String)),soldSet=sold(s);return players().filter(p=>String(p.role||'').toUpperCase()===r&&!soldSet.has(String(p.id))&&!used.has(String(p.id))&&obj.has(String(p.id))&&cardCredits(p)>0)}
function allAvailable(s,r,used){const soldSet=sold(s);return players().filter(p=>String(p.role||'').toUpperCase()===r&&!soldSet.has(String(p.id))&&!used.has(String(p.id))&&cardCredits(p)>0)}
function choose(s,st,t,used,cap){let list=t.priority==='bet'?allAvailable(s,t.r,used):candidates(s,t.r,used);if(t.priority==='bet'){const hard=Math.min(cap,betCap(s,st,t.r));list=list.filter(p=>cardCredits(p)<=hard);list.sort((a,b)=>{const av=score(a,s,t.r)/Math.max(1,cardCredits(a)),bv=score(b,s,t.r)/Math.max(1,cardCredits(b));return bv-av||score(b,s,t.r)-score(a,s,t.r)||cardCredits(a)-cardCredits(b)});return list[0]||null}const wanted=RANK[t.priority]??1;list.sort((a,b)=>{const ar=RANK[priority(s,a.id)]??1,br=RANK[priority(s,b.id)]??1;const ad=Math.abs(ar-wanted),bd=Math.abs(br-wanted);return ad-bd||br-ar||score(b,s,t.r)-score(a,s,t.r)||cardCredits(a)-cardCredits(b)});return list.find(p=>cardCredits(p)<=cap)||null}
function replaceExpensiveBets(s,st,used){ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach((t,i)=>{if(!t||t.priority!=='bet'||t.playerId==null)return;const p=players().find(x=>String(x.id)===String(t.playerId)),c=cardCredits(p),cap=betCap(s,st,r);if(c!=null&&c<=cap)return;used.delete(String(t.playerId));const alt=choose(s,st,{r,priority:'bet'},used,cap);if(alt){t.playerId=alt.id;st.slotBudgets[r][i]=cardCredits(alt);used.add(String(alt.id))}else{t.playerId=null;st.slotBudgets[r][i]=0}}))}
function sanitize(){const s=state(),st=strategy(s);if(!s||!st)return false;const used=new Set((mine(s)?.players||[]).map(p=>String(p.id)));ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach(t=>{if(t?.playerId!=null)used.add(String(t.playerId)}));replaceExpensiveBets(s,st,used);return syncCredits()}
function populateEmptyBets(s,st,used){let changed=false;ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach((t,i)=>{if(!t||t.priority!=='bet'||t.playerId!=null)return;const cap=betCap(s,st,r),list=allAvailable(s,r,used).filter(p=>cardCredits(p)<=cap);list.sort((a,b)=>{const av=score(a,s,r)/Math.max(1,cardCredits(a)),bv=score(b,s,r)/Math.max(1,cardCredits(b));return bv-av||score(b,s,r)-score(a,s,r)||cardCredits(a)-cardCredits(b)});const p=list[0];if(!p)return;t.playerId=p.id;st.slotBudgets[r][i]=cardCredits(p);used.add(String(p.id));changed=true}));return changed}
function syncRendererAllocations(){const s=state(),st=strategy(s);if(!s||!st)return false;let changed=false;ROLES.forEach(r=>{const n=Math.max(0,Math.round(Number(st.slots?.[r])||0)),plan=roleBudget(s,st,r);ensure(st,r,n);if(!st.slotAllocation||typeof st.slotAllocation!=='object')st.slotAllocation={};const arr=Array.isArray(st.slotAllocation[r])?st.slotAllocation[r].slice():Array(n).fill(0);while(arr.length<n)arr.push(0);for(let i=0;i<n;i++){const t=st.slotTargets[r][i],p=t?.playerId!=null?players().find(x=>String(x.id)===String(t.playerId)&&String(x.role||'').toUpperCase()===r):null,c=cardCredits(p),slot=document.querySelector('#brainContent .brain-role-row.role-'+r+' .brain-slot:nth-child('+(i+1)+')');if(slot?.classList.contains('purchased'))continue;const next=c!=null&&plan>0?(c/plan*100):0;if(Math.abs(Number(arr[i]||0)-next)>0.0000001){arr[i]=next;changed=true}if(c!=null&&Number(st.slotBudgets[r][i])!==c){st.slotBudgets[r][i]=c;changed=true}}st.slotAllocation[r]=arr});return changed}
function patchVisibleCredits(){const s=state(),st=strategy(s);if(!s||!st)return false;let changed=false;ROLES.forEach(r=>{const row=document.querySelector('#brainContent .brain-role-row.role-'+r);if(!row)return;const plan=roleBudget(s,st,r);[...row.querySelectorAll('.brain-slot')].forEach((slot,i)=>{if(slot.classList.contains('purchased'))return;const nameEl=slot.querySelector('.brain-slot-player');if(!nameEl)return;const name=String(nameEl.textContent||'').trim();const p=name&&name.toLowerCase()!=='scegli giocatore'?players().find(x=>String(x.name||'').trim().toLowerCase()===name.toLowerCase()&&String(x.role||'').toUpperCase()===r):null;const c=cardCredits(p);const budgetEl=slot.querySelector('.brain-slot-budget');const pctEl=slot.querySelector('.brain-slot-percent input');const target=st.slotTargets?.[r]?.[i];if(c!=null){const pct=plan>0?Math.round(c/plan*100):0;if(budgetEl&&String(budgetEl.textContent).trim()!==String(c)){budgetEl.textContent=String(c);changed=true}if(pctEl&&String(pctEl.value)!==String(pct)){pctEl.value=String(pct);changed=true}if(st.slotBudgets?.[r]&&Number(st.slotBudgets[r][i])!==c){st.slotBudgets[r][i]=c;changed=true}}else if(!target?.playerId){if(budgetEl&&String(budgetEl.textContent).trim()!=='0'){budgetEl.textContent='0';changed=true}if(pctEl&&String(pctEl.value)!=='0'){pctEl.value='0';changed=true}}});});return changed}
function installRenderHook(){if(typeof window.renderBrain!=='function')return false;if(window.renderBrain.__brainEngine3103)return true;const old=window.renderBrain;const wrapped=function(){const s=state(),st=strategy(s);if(s&&st){sanitize();syncRendererAllocations()}const out=old.apply(this,arguments);setTimeout(function(){const s2=state(),st2=strategy(s2);if(s2&&st2){sanitize();syncRendererAllocations();patchVisibleCredits()}},0);return out};wrapped.__brainEngine3103=true;window.renderBrain=wrapped;return true}
function fill(){if(busy)return;const s=state(),st=strategy(s);if(!s||!st)return;busy=true;try{const used=new Set((mine(s)?.players||[]).map(p=>String(p.id)));ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach(t=>{if(t?.playerId!=null)used.add(String(t.playerId)}));replaceExpensiveBets(s,st,used);populateEmptyBets(s,st,used);const tasks=[];ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach((t,i)=>{if(t?.playerId==null)tasks.push({r,i,priority:t?.priority||'base'})}));tasks.sort((a,b)=>(RANK[b.priority]??0)-(RANK[a.priority]??0)||ROLES.indexOf(a.r)-ROLES.indexOf(b.r)||a.i-b.i);const available={};ROLES.forEach(r=>available[r]=Math.max(0,roleBudget(s,st,r)-roleSpent(s,r)));const totalInitial=Math.max(0,Math.round((Number(s.initialCredits)||1200)-(Number(mine(s)?.spent)||0)));let totalLeft=totalInitial;for(const t of tasks){const cap=Math.min(available[t.r]||0,totalLeft);const p=choose(s,st,t,used,cap);if(!p)continue;const cost=cardCredits(p);if(cost==null||cost>cap)continue;t.playerId=p.id;st.slotBudgets[t.r][t.i]=cost;used.add(String(p.id));available[t.r]-=cost;totalLeft-=cost}sanitize();syncRendererAllocations();if(typeof window.persist==='function')window.persist();else localStorage.setItem('AF_CURRENT',JSON.stringify(s));if(typeof window.renderBrain==='function')setTimeout(window.renderBrain,0)}finally{busy=false}}
function patch(){installRenderHook();const s=state(),st=strategy(s);if(s&&st){const used=new Set((mine(s)?.players||[]).map(p=>String(p.id)));ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach(t=>{if(t?.playerId!=null)used.add(String(t.playerId)}));populateEmptyBets(s,st,used);sanitize();syncRendererAllocations();patchVisibleCredits()}const v=document.querySelector('.app-version');if(v)v.textContent='V. '+VERSION}
function boot(){patch();setTimeout(function(){installRenderHook();if(typeof window.renderBrain==='function')window.renderBrain()},120)}
window.BrainEngine={version:VERSION,syncCredits,fill,patch,patchVisibleCredits};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
