/* Brain engine 3.5.82 — prezzi target sempre dalla scheda giocatore */
(function(){
'use strict';
const VERSION='3.5.82',ROLES=['P','D','C','A'],RANK={max:4,high:3,low:2,base:2,bet:1};
let busy=false;
function state(){try{return(typeof current!=='undefined'&&current)||JSON.parse(localStorage.getItem('AF_CURRENT')||'null')}catch(e){return null}}
function players(){try{return typeof window.allPlayers==='function'?window.allPlayers():[]}catch(e){return[]}}
function strategy(s){return(s?.brainStrategies||[]).find(x=>Number(x.id)===Number(s.activeBrainStrategyId))||null}
function mine(s){return(s?.teams||[]).find(t=>Number(t.id)===Number(s.myTeamId))||(s?.teams||[])[0]||null}
function sold(s){const x=new Set();(s?.teams||[]).forEach(t=>(t.players||[]).forEach(p=>x.add(String(p.id))));return x}
function priority(s,id){try{const v=window.objectivePriority?.(id);if(RANK[v]!=null)return v}catch(e){}const v=s?.objectivePriorities?.[id]??s?.objectivePriorities?.[String(id)];return RANK[v]!=null?v:'low'}
function allocation(st,r){const a=st?.baseAllocation&&typeof st.baseAllocation==='object'?st.baseAllocation:(st?.allocation||{});return Math.max(0,Number(a[r])||0)}
function roleBudget(s,st,r){return Math.max(0,Math.round((Number(s?.initialCredits)||1200)*allocation(st,r)/100))}
function capFor(s,st,r){return Math.max(30,Math.round(roleBudget(s,st,r)*.10))}
function ensure(st,r,n){st.slotTargets=st.slotTargets&&typeof st.slotTargets==='object'?st.slotTargets:{};st.slotTargets[r]=Array.isArray(st.slotTargets[r])?st.slotTargets[r]:[];while(st.slotTargets[r].length<n)st.slotTargets[r].push({priority:'base',playerId:null});st.slotTargets[r]=st.slotTargets[r].slice(0,n);st.slotBudgets=st.slotBudgets&&typeof st.slotBudgets==='object'?st.slotBudgets:{};st.slotBudgets[r]=Array.isArray(st.slotBudgets[r])?st.slotBudgets[r]:[];while(st.slotBudgets[r].length<n)st.slotBudgets[r].push(0);st.slotBudgets[r]=st.slotBudgets[r].slice(0,n);st.slotBudgetManual=st.slotBudgetManual&&typeof st.slotBudgetManual==='object'?st.slotBudgetManual:{};st.slotBudgetManual[r]=Array.isArray(st.slotBudgetManual[r])?st.slotBudgetManual[r]:[];while(st.slotBudgetManual[r].length<n)st.slotBudgetManual[r].push(false);st.slotBudgetManual[r]=st.slotBudgetManual[r].slice(0,n)}
function findPlayer(s,st,r,i,slot){const id=st?.slotTargets?.[r]?.[i]?.playerId;if(id!=null){const p=players().find(x=>String(x.id)===String(id)&&String(x.role||'').toUpperCase()===r);if(p)return p}const el=slot?.querySelector?.('.brain-slot-player');const name=String(el?.textContent||'').trim();if(!name||name==='Scegli giocatore')return null;const n=name.toLowerCase();return players().find(x=>String(x.name||'').trim().toLowerCase()===n&&String(x.role||'').toUpperCase()===r)||players().find(x=>String(x.name||'').trim().toLowerCase()===n)||null}
function syncCredits(){const s=state(),st=strategy(s);if(!s||!st)return false;let changed=false;ROLES.forEach(r=>{const n=Math.max(0,Math.round(Number(st.slots?.[r])||0));ensure(st,r,n);const row=document.querySelector('#brainContent .brain-role-row.role-'+r);if(!row)return;[...row.querySelectorAll('.brain-slot')].forEach((slot,i)=>{if(slot.classList.contains('purchased')||slot.classList.contains('is-frozen'))return;const p=findPlayer(s,st,r,i,slot);if(!p)return;const c=Math.max(0,Math.round(Number(p.credits)||0));if(st.slotBudgetManual?.[r]?.[i]===true)st.slotBudgetManual[r][i]=false;if(Number(st.slotBudgets[r][i])!==c){st.slotBudgets[r][i]=c;changed=true}const b=slot.querySelector('.brain-slot-budget,.brain-slot-budget-input');if(b){if('value' in b)b.value=String(c);b.textContent=String(c)}const plan=roleBudget(s,st,r),pct=plan>0?Math.round(c/plan*100):0;const pi=slot.querySelector('.brain-slot-percent input');if(pi)pi.value=String(pct)})});return changed}
function score(p,s,r){const my=mine(s),same=(my?.players||[]).some(x=>x.role===r&&String(x.realTeam||x.team||'').toLowerCase()===String(p.team||'').toLowerCase());return(Number(p.appeal)||0)*18+(same?-9:5)}
function candidates(s,st,r,required,used){const obj=new Set((s.objectives||[]).map(String)),soldSet=sold(s),pool=players().filter(p=>String(p.role||'').toUpperCase()===r&&!soldSet.has(String(p.id))&&!used.has(String(p.id))&&obj.has(String(p.id))&&Number(p.credits)>0);const exact=pool.filter(p=>priority(s,p.id)===required);return exact.length?exact:pool}
function choose(s,st,t,used,cap){let list=candidates(s,st,t.r,t.priority,used);if(t.priority==='bet'){const hard=Math.min(cap,capFor(s,st,t.r));list=list.filter(p=>Math.round(Number(p.credits)||0)<=hard);list.sort((a,b)=>{const ac=Math.max(1,Number(a.credits)||1),bc=Math.max(1,Number(b.credits)||1);return score(b,s,t.r)/bc-score(a,s,t.r)/ac||score(b,s,t.r)-score(a,s,t.r)||ac-bc});return list[0]||null}list=list.filter(p=>Math.round(Number(p.credits)||0)<=cap);list.sort((a,b)=>score(b,s,t.r)-score(a,s,t.r)||Number(b.appeal||0)-Number(a.appeal||0)||Number(a.credits)-Number(b.credits));return list[0]||null}
function replaceExpensiveBets(s,st,used){ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach((t,i)=>{if(!t||t.priority!=='bet'||t.playerId==null)return;const p=players().find(x=>String(x.id)===String(t.playerId)),c=Math.round(Number(p?.credits)||0),cap=capFor(s,st,r);if(c<=cap)return;used.delete(String(t.playerId));const alt=choose(s,st,{r,priority:'bet'},used,cap);if(alt){t.playerId=alt.id;st.slotBudgets[r][i]=Math.round(Number(alt.credits)||0);used.add(String(alt.id))}else{t.playerId=null;st.slotBudgets[r][i]=0}}))}
function fill(){if(busy)return;const s=state(),st=strategy(s);if(!s||!st)return;busy=true;try{const used=new Set((mine(s)?.players||[]).map(p=>String(p.id)));ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach(t=>{if(t?.playerId!=null)used.add(String(t.playerId)}));replaceExpensiveBets(s,st,used);const tasks=[];ROLES.forEach(r=>(st.slotTargets?.[r]||[]).forEach((t,i)=>{if(t?.playerId==null)tasks.push({r,i,priority:t?.priority||'low'})}));tasks.sort((a,b)=>(RANK[b.priority]||2)-(RANK[a.priority]||2)||ROLES.indexOf(a.r)-ROLES.indexOf(b.r));for(const t of tasks){const cap=roleBudget(s,st,t.r),p=choose(s,st,t,used,cap);if(!p)continue;t.playerId=p.id;st.slotBudgets[t.r][t.i]=Math.round(Number(p.credits)||0);used.add(String(p.id))}syncCredits();if(typeof window.persist==='function')window.persist();else{localStorage.setItem('AF_CURRENT',JSON.stringify(s));const db=JSON.parse(localStorage.getItem('AF_DB')||'[]'),i=db.findIndex(x=>Number(x.id)===Number(s.id));if(i>=0){db[i]=s;localStorage.setItem('AF_DB',JSON.stringify(db))}}if(typeof window.renderBrain==='function')setTimeout(window.renderBrain,0)}finally{busy=false}}
function patch(){syncCredits();const v=document.querySelector('.app-version');if(v)v.textContent='V. '+VERSION}
function boot(){patch();setInterval(patch,350)}
window.BrainEngine={version:VERSION,syncCredits,fill,patch};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();