/* ORACOLO 1.0.16 — motore Smart 3.5.36 */
(function(){
'use strict';
const VERSION='3.5.36',ROLES=['P','D','C','A'],ROLE_NAMES={P:'Portieri',D:'Difensori',C:'Centrocampisti',A:'Attaccanti'};
let busy=false,observer=null,renderWrapped=false;
function state(){try{return(typeof current!=='undefined'&&current)||JSON.parse(localStorage.getItem('AF_CURRENT')||'null')}catch(e){return null}}
function players(){try{return typeof window.allPlayers==='function'?window.allPlayers():[]}catch(e){return[]}}
function mine(s){return(s?.teams||[]).find(t=>Number(t.id)===Number(s.myTeamId))||(s?.teams||[])[0]||null}
function sold(s){const x=new Set();(s?.teams||[]).forEach(t=>(t.players||[]).forEach(p=>x.add(String(p.id))));return x}
function strategy(s){return(s?.brainStrategies||[]).find(x=>Number(x.id)===Number(s.activeBrainStrategyId))||null}
function slots(st,r){const n=Number(st?.slots?.[r]);return Number.isFinite(n)&&n>=0?Math.round(n):0}
function empty(v){return v==null||v===''||Number(v)===0}
function priority(s,id){try{return window.objectivePriority(id)||'base'}catch(e){return s?.objectivePriorities?.[id]||s?.objectivePriorities?.[String(id)]||'base'}}
function ensure(st,r,n){if(!st.slotTargets||typeof st.slotTargets!=='object')st.slotTargets={};if(!Array.isArray(st.slotTargets[r]))st.slotTargets[r]=[];while(st.slotTargets[r].length<n)st.slotTargets[r].push({priority:'base',playerId:null});st.slotTargets[r]=st.slotTargets[r].slice(0,n);if(!st.slotBudgets||typeof st.slotBudgets!=='object')st.slotBudgets={};if(!Array.isArray(st.slotBudgets[r]))st.slotBudgets[r]=[];while(st.slotBudgets[r].length<n)st.slotBudgets[r].push(0);st.slotBudgets[r]=st.slotBudgets[r].slice(0,n);if(!st.slotBudgetManual||typeof st.slotBudgetManual!=='object')st.slotBudgetManual={};if(!Array.isArray(st.slotBudgetManual[r]))st.slotBudgetManual[r]=[];while(st.slotBudgetManual[r].length<n)st.slotBudgetManual[r].push(false);st.slotBudgetManual[r]=st.slotBudgetManual[r].slice(0,n)}
function base(st){if(!st.baseAllocation||typeof st.baseAllocation!=='object')st.baseAllocation={...(st.allocation||{})};ROLES.forEach(r=>st.baseAllocation[r]=Math.max(0,Number(st.baseAllocation[r])||0));return st.baseAllocation}
function planned(s,st,r){return Math.round((Number(s.initialCredits)||1200)*base(st)[r]/100)}
function stats(id){try{const d=JSON.parse(localStorage.getItem('AF_ORACOLO_STATS')||'{}'),v=d[String(id)];return Array.isArray(v)?{pres:v[0],fm:v[2],goals:v[3],assists:v[4],pmv:v[9]}:(v||{})}catch(e){return{}}}
function score(p,s,r,pr){const q=stats(p.id),my=mine(s),owned=(my?.players||[]).filter(x=>x.role===r);const same=owned.filter(x=>String(x.realTeam||x.team||'').toLowerCase()===String(p.team||'').toLowerCase()).length;let v=(Number(p.appeal)||0)*18+Math.min(Number(q.pres)||0,38)*.9+(Number(q.goals)||0)*2.8+(Number(q.assists)||0)*2.6+(Number(q.fm)||0)*4.5+(Number(q.pmv)||Number(p.pmv)||0)*.05-same*9;if(!same)v+=5;try{if(window.objectivePriority(p.id)===pr)v+=20}catch(e){}return v}
function pool(s,r,used,pr){const soldSet=sold(s),obj=new Set((s.objectives||[]).map(x=>String(x)));const all=players().filter(p=>p.role===r&&!soldSet.has(String(p.id))&&!used.has(String(p.id)));const exact=all.filter(p=>obj.has(String(p.id))&&priority(s,p.id)===pr);if(exact.length)return exact;const objective=all.filter(p=>obj.has(String(p.id)));return objective.length?objective:all}
function choose(s,st,r,i,used){const wanted=st.slotTargets?.[r]?.[i]?.priority||'base';let list=pool(s,r,used,wanted);return list.sort((a,b)=>score(b,s,r,wanted)-score(a,s,r,wanted))[0]||null}
function distribute(st,r,candidates,budget){const n=candidates.length,arr=st.slotBudgets[r],manual=st.slotBudgetManual[r];let fixed=0,auto=[];candidates.forEach(x=>{if(!x.p)return;if(manual[x.i])fixed+=Math.max(0,Math.round(Number(arr[x.i])||0));else auto.push(x)});let remaining=Math.max(0,Math.round(budget-fixed));const weights=auto.map(x=>({x,w:Math.max(1,Number(x.p.credits)||1)})),sum=weights.reduce((a,z)=>a+z.w,0)||1;weights.forEach(z=>arr[z.x.i]=Math.floor(remaining*z.w/sum));let used=weights.reduce((a,z)=>a+arr[z.x.i],0),left=remaining-used;for(const z of weights){if(left<=0)break;arr[z.x.i]++;left--}for(let i=0;i<n;i++)if(!candidates[i].p)arr[i]=0}
function fill(){if(busy)return;const s=state(),st=strategy(s);if(!s||!st)return;busy=true;let changed=false;const used=new Set((mine(s)?.players||[]).map(p=>String(p.id))),data={};
base(st);ROLES.forEach(r=>{const n=slots(st,r);if(!n)return;ensure(st,r,n);const ts=st.slotTargets[r];const candidates=[];let missing=0,theoretical=0;for(let i=0;i<n;i++){let p=!empty(ts[i]?.playerId)?players().find(x=>String(x.id)===String(ts[i].playerId)):null;if(p&&sold(s).has(String(p.id)))p=null;if(!p){p=choose(s,st,r,i,used);if(p){ts[i].playerId=p.id;used.add(String(p.id));changed=true}else missing++}if(p){theoretical+=Math.max(0,Math.round(Number(p.credits)||0));candidates.push({i,p})}else candidates.push({i,p:null})}data[r]={n,candidates,theoretical,missing};const roleBudget=planned(s,st,r);const before=st.slotBudgets[r].slice();distribute(st,r,candidates,roleBudget);for(let i=0;i<n;i++)if(before[i]!==st.slotBudgets[r][i])changed=true;st.slotAllocation=st.slotAllocation||{};st.slotAllocation[r]=st.slotBudgets[r].map(v=>roleBudget>0?Math.round(Number(v||0)/roleBudget*100):0)});
const suggestions=[];ROLES.forEach(r=>{const d=data[r];if(!d)return;const budget=planned(s,st,r),surplus=Math.max(0,budget-d.theoretical);if(!surplus)return;const same=pool(s,r,new Set(d.candidates.filter(x=>x.p).map(x=>String(x.p.id))),'base').sort((a,b)=>score(b,s,r,priority(s,b.id))-score(a,s,r,priority(s,a.id)))[0];if(same)suggestions.push({type:'same',r,name:same.name,cost:Math.round(Number(same.credits)||0),surplus,score:score(same,s,r,priority(s,same.id))})});
const global=ROLES.flatMap(r=>{const d=data[r];return d?pool(s,r,new Set(d.candidates.filter(x=>x.p).map(x=>String(x.p.id))),'base').map(p=>({r,p,score:score(p,s,r,priority(s,p.id)),cost:Math.round(Number(p.credits)||0)})):[]}).sort((a,b)=>b.score-a.score);if(global.length){const best=global[0];const totalSurplus=ROLES.reduce((n,r)=>n+Math.max(0,(planned(s,st,r)-(data[r]?.theoretical||0))),0);if(totalSurplus>0&&!suggestions.some(x=>x.name===best.p.name))suggestions.push({type:'other',r:best.r,name:best.p.name,cost:best.cost,surplus:totalSurplus,score:best.score})}
st.reinvestSuggestions=suggestions;const over=ROLES.filter(r=>data[r]&&data[r].theoretical>planned(s,st,r));const miss=ROLES.filter(r=>data[r]?.missing>0);if(changed)persist(s);setTimeout(()=>{busy=false;if(typeof window.renderBrain==='function')window.renderBrain();let msg='Oracolo ha aggiornato le proposte in base ai crediti e agli acquisti reali.';if(over.length){msg+='\n\n⚠️ Costo teorico oltre il budget:';over.forEach(r=>{msg+='\n'+ROLE_NAMES[r]+': '+data[r].theoretical+' / '+planned(s,st,r)})}if(miss.length){msg+='\n\n⚠️ Slot senza giocatore disponibile:';miss.forEach(r=>{msg+='\n'+ROLE_NAMES[r]+': '+data[r].missing})}if(suggestions.length){msg+='\n\n💡 Reinvestimento consigliato:';suggestions.slice(0,4).forEach(x=>{msg+='\n'+(x.type==='same'?'Stesso reparto':'Altro reparto')+' · '+ROLE_NAMES[x.r]+': '+x.name+' (~'+x.cost+')'})}alert(msg)},0)}
function persist(s){if(typeof window.persist==='function'){window.persist();return}localStorage.setItem('AF_CURRENT',JSON.stringify(s));try{const db=JSON.parse(localStorage.getItem('AF_DB')||'[]'),i=db.findIndex(x=>Number(x.id)===Number(s.id));if(i>=0){db[i]=s;localStorage.setItem('AF_DB',JSON.stringify(db))}}catch(e){}}
function addButton(){const s=state(),activeId=s?.activeBrainStrategyId;document.querySelectorAll('.brain-strategy').forEach(card=>{const name=card.querySelector('.brain-strategy-name');const onclick=String(name?.getAttribute('onclick')||'');const m=onclick.match(/toggleBrainStrategy\((\d+)\)/);const isActive=card.classList.contains('active')||(m&&Number(m[1])===Number(activeId));if(!isActive||card.querySelector('.oracolo-action'))return;const total=card.querySelector('.brain-total');const anchor=total||card.querySelector('.brain-strategy-title')||name;if(!anchor)return;const wrap=document.createElement('div');wrap.className='oracolo-action';const b=document.createElement('button');b.type='button';b.className='oracolo-button';b.innerHTML='<span class="oracolo-icon">🔮</span><span>Oracolo</span>';b.title='Aggiorna previsioni e reinvestimento';b.onclick=e=>{e.preventDefault();e.stopPropagation();fill()};wrap.appendChild(b);anchor.insertAdjacentElement('afterend',wrap)})}
function style(){if(document.getElementById('oracoloStyle'))return;const c=document.createElement('style');c.id='oracoloStyle';c.textContent='.oracolo-action{width:100%;margin:8px 0 10px;display:flex}.oracolo-button{width:100%;height:38px;padding:0 12px;border:1px solid rgba(93,63,145,.28);border-radius:11px;background:linear-gradient(135deg,#fff,#f2edff);color:#5b3b8f;font-weight:850;font-size:14px;display:flex;align-items:center;justify-content:center;gap:6px}.oracolo-button:active{transform:scale(.98)}.oracolo-icon{font-size:19px;line-height:1}';document.head.appendChild(c)}
function watch(){if(observer||!document.body)return;observer=new MutationObserver(addButton);observer.observe(document.getElementById('brainContent')||document.body,{childList:true,subtree:true});addButton()}
function boot(){style();if(renderWrapped)return;const old=window.renderBrain;if(typeof old==='function'){window.renderBrain=function(){const x=old.apply(this,arguments);setTimeout(addButton,0);return x};renderWrapped=true;window.renderBrain();watch()}else setTimeout(boot,100)}
window.Oracolo={version:VERSION,run:fill,referenceCost:p=>Number(p?.credits)||0};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
