/* ORACOLO 1.0.20 — motore Smart 3.5.43 */
(function(){
'use strict';
const VERSION='3.5.43',ROLES=['P','D','C','A'],ROLE_NAMES={P:'Portieri',D:'Difensori',C:'Centrocampisti',A:'Attaccanti'},PRIORITY_RANK={max:5,high:4,low:3,base:2,bet:1};
let busy=false,observer=null,renderWrapped=false;
function state(){try{return(typeof current!=='undefined'&&current)||JSON.parse(localStorage.getItem('AF_CURRENT')||'null')}catch(e){return null}}
function players(){try{return typeof window.allPlayers==='function'?window.allPlayers():[]}catch(e){return[]}}
function mine(s){return(s?.teams||[]).find(t=>Number(t.id)===Number(s.myTeamId))||(s?.teams||[])[0]||null}
function sold(s){const x=new Set();(s?.teams||[]).forEach(t=>(t.players||[]).forEach(p=>x.add(String(p.id))));return x}
function strategy(s){return(s?.brainStrategies||[]).find(x=>Number(x.id)===Number(s.activeBrainStrategyId))||null}
function slots(st,r){const n=Number(st?.slots?.[r]);return Number.isFinite(n)&&n>=0?Math.round(n):0}
function priority(s,id){try{const v=window.objectivePriority(id);if(v)return v}catch(e){}return s?.objectivePriorities?.[id]??s?.objectivePriorities?.[String(id)]??'base'}
function ensure(st,r,n){if(!st.slotTargets||typeof st.slotTargets!=='object')st.slotTargets={};if(!Array.isArray(st.slotTargets[r]))st.slotTargets[r]=[];while(st.slotTargets[r].length<n)st.slotTargets[r].push({priority:'base',playerId:null});st.slotTargets[r]=st.slotTargets[r].slice(0,n);if(!st.slotBudgets||typeof st.slotBudgets!=='object')st.slotBudgets={};if(!Array.isArray(st.slotBudgets[r]))st.slotBudgets[r]=[];while(st.slotBudgets[r].length<n)st.slotBudgets[r].push(0);st.slotBudgets[r]=st.slotBudgets[r].slice(0,n);if(!st.slotBudgetManual||typeof st.slotBudgetManual!=='object')st.slotBudgetManual={};if(!Array.isArray(st.slotBudgetManual[r]))st.slotBudgetManual[r]=[];while(st.slotBudgetManual[r].length<n)st.slotBudgetManual[r].push(false);st.slotBudgetManual[r]=st.slotBudgetManual[r].slice(0,n)}
function base(st){if(!st.baseAllocation||typeof st.baseAllocation!=='object')st.baseAllocation={...(st.allocation||{})};ROLES.forEach(r=>st.baseAllocation[r]=Math.max(0,Number(st.baseAllocation[r])||0));return st.baseAllocation}
function planned(s,st,r){return Math.round((Number(s.initialCredits)||1200)*base(st)[r]/100)}
function stats(id){try{const d=JSON.parse(localStorage.getItem('AF_ORACOLO_STATS')||'{}'),v=d[String(id)];return Array.isArray(v)?{pres:v[0],fm:v[2],goals:v[3],assists:v[4]}:(v||{})}catch(e){return{}}}
function score(p,s,r,pr){const q=stats(p.id),my=mine(s),owned=(my?.players||[]).filter(x=>x.role===r);const same=owned.filter(x=>String(x.realTeam||x.team||'').toLowerCase()===String(p.team||'').toLowerCase()).length;let v=(Number(p.appeal)||0)*18+Math.min(Number(q.pres)||0,38)*.9+(Number(q.goals)||0)*2.8+(Number(q.assists)||0)*2.6+(Number(q.fm)||0)*4.5-same*9;if(!same)v+=5;return v}
function pool(s,r,used,pr){const soldSet=sold(s),obj=new Set((s.objectives||[]).map(x=>String(x)));return players().filter(p=>p.role===r&&!soldSet.has(String(p.id))&&!used.has(String(p.id))&&obj.has(String(p.id))&&priority(s,p.id)===pr&&Number(p.credits)>0)}
function selectSet(s,st,r,used){const n=slots(st,r),budget=planned(s,st,r),targets=(st.slotTargets?.[r]||[]).slice(0,n),order=Array.from({length:n},(_,i)=>i).sort((a,b)=>(PRIORITY_RANK[targets[b]?.priority||'base']||2)-(PRIORITY_RANK[targets[a]?.priority||'base']||2)||a-b),lists=targets.map((t)=>pool(s,r,used,t?.priority||'base'));let best=null;
function vector(items){const filled=new Array(n).fill(0);items.forEach(x=>filled[x.i]=1);const groups=[5,4,3,2,1],v=[];groups.forEach(rank=>{let c=0;for(let i=0;i<n;i++)if((PRIORITY_RANK[targets[i]?.priority||'base']||2)===rank&&filled[i])c++;v.push(c)});v.push(items.length);return v}
function better(a,b){if(!b)return true;const va=vector(a.items),vb=vector(b.items);for(let i=0;i<va.length;i++){if(va[i]!==vb[i])return va[i]>vb[i]}if(a.value!==b.value)return a.value>b.value;return a.cost>b.cost}
function consider(items,cost,value){if(cost>budget)return;const cand={items:items.slice(),cost,value};if(better(cand,best))best=cand}
function dfs(k,chosen,cost,value,ids){if(cost>budget)return;if(k===order.length){consider(chosen,cost,value);return}const i=order[k],pr=targets[i]?.priority||'base',list=lists[i].slice().sort((a,b)=>score(b,s,r,pr)-score(a,s,r,pr));dfs(k+1,chosen,cost,value,ids);for(const p of list){const id=String(p.id);if(ids.has(id))continue;const pc=Math.max(0,Math.round(Number(p.credits)||0));if(!pc||cost+pc>budget)continue;ids.add(id);chosen.push({i,p});dfs(k+1,chosen,cost+pc,value+score(p,s,r,pr),ids);chosen.pop();ids.delete(id)}}
dfs(0,[],0,0,new Set(used));return best||{items:[],cost:0,value:0,possible:false,missing:n}}
function setAllocation(st,r,items){const arr=new Array(slots(st,r)).fill(0),total=items.reduce((a,x)=>a+Math.max(0,Math.round(Number(x.p.credits)||0)),0);if(!total)return arr;const parts=items.map(x=>({i:x.i,v:Math.max(0,Math.round(Number(x.p.credits)||0)),frac:x.p.credits/total}));let sum=0;parts.forEach(x=>{arr[x.i]=Math.floor(x.frac*100);sum+=arr[x.i]});parts.sort((a,b)=>(b.frac*100-Math.floor(b.frac*100))-(a.frac*100-Math.floor(a.frac*100)));for(let k=0;k<100-sum;k++)arr[parts[k%parts.length].i]++;return arr}
function cheapestNeed(s,r,pr,used){return pool(s,r,used,pr).slice().sort((a,b)=>Number(a.credits)-Number(b.credits))[0]||null}
function strategyAdvice(s,st,data){const missing=data.filter(x=>x.missing>0);if(!missing.length)return[];const used=new Set((mine(s)?.players||[]).map(p=>String(p.id)));data.forEach(x=>(x.items||[]).forEach(it=>used.add(String(it.p.id))));const needs=[];missing.forEach(x=>{const targets=st.slotTargets?.[x.r]||[];let need=0,available=true;for(let i=0;i<targets.length;i++){if((x.items||[]).some(it=>it.i===i))continue;const pr=targets[i]?.priority||'base',p=cheapestNeed(s,x.r,pr,used);if(!p){available=false;break}need+=Math.max(0,Math.round(Number(p.credits)||0));used.add(String(p.id))}if(available&&need>0)needs.push({r:x.r,need})});const donors=data.filter(x=>x.missing===0&&x.theoretical>0).map(x=>({r:x.r,surplus:Math.max(0,x.budget-x.theoretical)})).filter(x=>x.surplus>0).sort((a,b)=>b.surplus-a.surplus);const out=[];needs.forEach(n=>{let left=n.need;for(const d of donors){if(left<=0)break;const move=Math.min(left,d.surplus);if(move>0){out.push({from:d.r,to:n.r,amount:move});left-=move;d.surplus-=move}}if(left>0)out.push({from:null,to:n.r,amount:left})});return out}
function fill(){if(busy)return;const s=state(),st=strategy(s);if(!s||!st)return;busy=true;let changed=false;const used=new Set((mine(s)?.players||[]).map(p=>String(p.id))),data=[];base(st);ROLES.forEach(r=>{const n=slots(st,r);if(!n)return;ensure(st,r,n);const result=selectSet(s,st,r,used),items=result.items||[],ts=st.slotTargets[r];for(let i=0;i<n;i++){const found=items.find(x=>x.i===i),nextId=found?found.p.id:null;if(String(ts[i]?.playerId??'')!==String(nextId??'')){ts[i].playerId=nextId;changed=true}if(found)used.add(String(found.p.id));if(!found&&!st.slotBudgetManual[r][i]&&Number(st.slotBudgets[r][i])!==0){st.slotBudgets[r][i]=0;changed=true}}const roleBudget=planned(s,st,r),before=st.slotBudgets[r].slice();items.forEach(x=>{const v=Math.max(0,Math.round(Number(x.p.credits)||0));if(!st.slotBudgetManual[r][x.i]&&Number(st.slotBudgets[r][x.i])!==v){st.slotBudgets[r][x.i]=v;changed=true}});st.slotAllocation=st.slotAllocation||{};st.slotAllocation[r]=setAllocation(st,r,items);for(let i=0;i<n;i++)if(before[i]!==st.slotBudgets[r][i])changed=true;data.push({r,n,items,theoretical:items.reduce((a,x)=>a+Math.max(0,Math.round(Number(x.p.credits)||0)),0),budget:roleBudget,possible:items.length===n,missing:n-items.length})});st.reinvestSuggestions=[];if(changed)persist(s);setTimeout(()=>{busy=false;if(typeof window.renderBrain==='function')window.renderBrain();let msg='Oracolo ha aggiornato le proposte dando priorità agli slot con appetibilità più alta e rispettando il budget del reparto.';const warnings=data.filter(x=>x.missing>0);if(warnings.length){msg+='\n\n⚠️ Alcuni slot non sono completabili con la strategia attuale:';warnings.forEach(x=>{msg+='\n'+ROLE_NAMES[x.r]+': '+x.theoretical+' / '+x.budget+' crediti · slot mancanti '+x.missing});const advice=strategyAdvice(s,st,data);msg+='\n\n💡 Cambio strategia consigliato:';if(advice.length)advice.forEach(a=>{if(a.from)msg+='\nSpostare circa '+a.amount+' crediti da '+ROLE_NAMES[a.from]+' a '+ROLE_NAMES[a.to]+'.';else msg+='\nPer '+ROLE_NAMES[a.to]+' servirebbero ancora circa '+a.amount+' crediti: non c’è copertura sufficiente negli altri reparti.'});else msg+='\nValuta di abbassare il budget di un altro reparto e aumentare quello del reparto incompleto, oppure ridurre l’appetibilità di uno slot.'}alert(msg)},0)}
function persist(s){if(typeof window.persist==='function'){window.persist();return}localStorage.setItem('AF_CURRENT',JSON.stringify(s));try{const db=JSON.parse(localStorage.getItem('AF_DB')||'[]'),i=db.findIndex(x=>Number(x.id)===Number(s.id));if(i>=0){db[i]=s;localStorage.setItem('AF_DB',JSON.stringify(db))}}catch(e){}}
function addButton(){const s=state(),activeId=s?.activeBrainStrategyId;document.querySelectorAll('.brain-strategy').forEach(card=>{const name=card.querySelector('.brain-strategy-name'),onclick=String(name?.getAttribute('onclick')||''),m=onclick.match(/toggleBrainStrategy\((\d+)\)/),isActive=card.classList.contains('active')||(m&&Number(m[1])===Number(activeId));if(!isActive||card.querySelector('.oracolo-action'))return;const total=card.querySelector('.brain-total'),anchor=total||card.querySelector('.brain-strategy-title')||name;if(!anchor)return;const wrap=document.createElement('div');wrap.className='oracolo-action';const b=document.createElement('button');b.type='button';b.className='oracolo-button';b.innerHTML='<span class="oracolo-icon">🔮</span><span>Oracolo</span>';b.title='Aggiorna previsioni e budget';b.onclick=e=>{e.preventDefault();e.stopPropagation();fill()};wrap.appendChild(b);anchor.insertAdjacentElement('afterend',wrap)})}
function style(){if(document.getElementById('oracoloStyle'))return;const c=document.createElement('style');c.id='oracoloStyle';c.textContent='.oracolo-action{width:100%;margin:8px 0 10px;display:flex}.oracolo-button{width:100%;height:38px;padding:0 12px;border:1px solid rgba(93,63,145,.28);border-radius:11px;background:linear-gradient(135deg,#fff,#f2edff);color:#5b3b8f;font-weight:850;font-size:14px;display:flex;align-items:center;justify-content:center;gap:6px}.oracolo-button:active{transform:scale(.98)}.oracolo-icon{font-size:19px;line-height:1}';document.head.appendChild(c)}
function watch(){if(observer||!document.body)return;observer=new MutationObserver(addButton);observer.observe(document.getElementById('brainContent')||document.body,{childList:true,subtree:true});addButton()}
function boot(){style();if(renderWrapped)return;const old=window.renderBrain;if(typeof old==='function'){window.renderBrain=function(){const x=old.apply(this,arguments);setTimeout(addButton,0);return x};renderWrapped=true;window.renderBrain();watch()}else setTimeout(boot,100)}
window.Oracolo={version:VERSION,run:fill,referenceCost:p=>Number(p?.credits)||0};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
